<a href="https://colab.research.google.com/github/PavaniMaganti/AI-Healthcare-Guidance-Application/blob/main/Health_care_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

In [ ]:
df = pd.read_csv("healthcare_training_dataset.csv")

df.head()

,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,continuous_sneezing,shivering,chills,watering_from_eyes,stomach_pain,acidity,...,bladder_discomfort,foul_smell_of urine,continuous_feel_of_urine,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,disease
0,1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection

In [ ]:
print("Dataset shape:", df.shape)
print("Number of columns:", len(df.columns))
print("First 10 columns:")
print(df.columns[:10])
print("Last 5 columns:")
print(df.columns[-5:])

Dataset shape: (861, 131)
Number of columns: 131
First 10 columns:
Index(['itching', 'skin_rash', 'nodal_skin_eruptions', 'dischromic _patches',
       'continuous_sneezing', 'shivering', 'chills', 'watering_from_eyes',
       'stomach_pain', 'acidity'],
      dtype='object')
Last 5 columns:
Index(['small_dents_in_nails', 'inflammatory_nails', 'blister',
       'red_sore_around_nose', 'disease'],
      dtype='object')

In [ ]:
print("Number of diseases:", df["disease"].nunique())
print(df["disease"].value_counts().head(10))

Number of diseases: 41
disease
Fungal infection       21
Allergy                21
GERD                   21
Chronic cholestasis    21
Drug Reaction          21
Peptic ulcer diseae    21
AIDS                   21
Diabetes               21
Gastroenteritis        21
Bronchial Asthma       21
Name: count, dtype: int64

In [ ]:
print("Dataset shape:", df.shape)

print("\nTotal missing values:")
print(df.isnull().sum().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nDisease count minimum:", df["disease"].value_counts().min())
print("Disease count maximum:", df["disease"].value_counts().max())

symptom_columns = [col for col in df.columns if col != "disease"]

print("\nNumber of symptom columns:", len(symptom_columns))

# Check whether symptom columns only contain 0 and 1
valid_binary = df[symptom_columns].isin([0, 1]).all().all()
print("Are all symptom columns binary 0/1?", valid_binary)

Dataset shape: (861, 131)

Total missing values:
0

Duplicate rows:
231

Disease count minimum: 21
Disease count maximum: 21

Number of symptom columns: 130
Are all symptom columns binary 0/1? True

In [ ]:
df["disease"] = df["disease"].replace({
    "Peptic ulcer diseae": "Peptic ulcer disease"
})

print(df["disease"].unique())

['Fungal infection' 'Allergy' 'GERD' 'Chronic cholestasis' 'Drug Reaction'
 'Peptic ulcer disease' 'AIDS' 'Diabetes' 'Gastroenteritis'
 'Bronchial Asthma' 'Hypertension' 'Migraine' 'Cervical spondylosis'
 'Paralysis (brain hemorrhage)' 'Jaundice' 'Malaria' 'Chicken pox'
 'Dengue' 'Typhoid' 'hepatitis A' 'Hepatitis B' 'Hepatitis C'
 'Hepatitis D' 'Hepatitis E' 'Alcoholic hepatitis' 'Tuberculosis'
 'Common Cold' 'Pneumonia' 'Dimorphic hemmorhoids(piles)' 'Heart attack'
 'Varicose veins' 'Hypothyroidism' 'Hyperthyroidism' 'Hypoglycemia'
 'Osteoarthristis' 'Arthritis' '(vertigo) Paroymsal  Positional Vertigo'
 'Acne' 'Urinary tract infection' 'Psoriasis' 'Impetigo']

In [ ]:
print("Before removing duplicates:", df.shape)

df = df.drop_duplicates()

print("After removing duplicates:", df.shape)
print("Duplicates remaining:", df.duplicated().sum())

Before removing duplicates: (861, 131)
After removing duplicates: (630, 131)
Duplicates remaining: 0

In [ ]:
print("Number of diseases:", df["disease"].nunique())

disease_counts = df["disease"].value_counts()

print("Minimum examples per disease:", disease_counts.min())
print("Maximum examples per disease:", disease_counts.max())

disease_counts

Number of diseases: 41
Minimum examples per disease: 9
Maximum examples per disease: 21

disease
Dengue                                     21
Hyperthyroidism                            21
Tuberculosis                               19
Chicken pox                                19
Hepatitis D                                19
Bronchial Asthma                           19
Typhoid                                    19
hepatitis A                                19
Diabetes                                   19
Pneumonia                                  19
Hypothyroidism                             19
Hypoglycemia                               19
Osteoarthristis                            18
Peptic ulcer disease                       18
Alcoholic hepatitis                        17
Hepatitis C                                17
Common Cold                                17
Hepatitis E                                17
Hepatitis B                                16
Jaundice                                   16
Migraine                                   16
(vertigo) Paroymsal  Positional Vertigo    16
Impetigo                                   15
Allergy                                    15
Malaria                                    15
GERD                                       14
Fungal infection                           14
Chronic cholestasis                        14
Gastroenteritis                            13
Heart attack                               13
Psoriasis                                  13
Hypertension                               13
Cervical spondylosis                       11
Urinary tract infection                    11
Varicose veins                             11
Paralysis (brain hemorrhage)               10
Drug Reaction                              10
Arthritis                                  10
Dimorphic hemmorhoids(piles)               10
AIDS                                        9
Acne                                        9
Name: count, dtype: int64

In [ ]:
# Features = symptom columns
X = df.drop(columns=["disease"])

# Target = disease column
y = df["disease"]

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nFirst 5 target values:")
print(y.head())

X shape: (630, 130)
y shape: (630,)

First 5 target values:
0    Fungal infection
1    Fungal infection
2    Fungal infection
3    Fungal infection
4    Fungal infection
Name: disease, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_encoded = label_encoder.fit_transform(y)

print("Original disease names:")
print(y.head())

print("\nEncoded disease labels:")
print(y_encoded[:10])

print("\nNumber of classes:", len(label_encoder.classes_))

print("\nFirst 10 disease classes:")
print(label_encoder.classes_[:10])

Original disease names:
0    Fungal infection
1    Fungal infection
2    Fungal infection
3    Fungal infection
4    Fungal infection
Name: disease, dtype: object

Encoded disease labels:
[15 15 15 15 15 15 15 15 15 15]

Number of classes: 41

First 10 disease classes:
['(vertigo) Paroymsal  Positional Vertigo' 'AIDS' 'Acne'
 'Alcoholic hepatitis' 'Allergy' 'Arthritis' 'Bronchial Asthma'
 'Cervical spondylosis' 'Chicken pox' 'Chronic cholestasis']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)
print("Training labels:", y_train.shape)
print("Testing labels:", y_test.shape)

Training data: (504, 130)
Testing data: (126, 130)
Training labels: (504,)
Testing labels: (126,)

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Create SVM model
svm_model = SVC(kernel="linear", probability=True, random_state=42)

# Train the model
svm_model.fit(X_train, y_train)

# Predict on test data
svm_predictions = svm_model.predict(X_test)

# Evaluate
svm_accuracy = accuracy_score(y_test, svm_predictions)
svm_precision = precision_score(y_test, svm_predictions, average="weighted", zero_division=0)
svm_recall = recall_score(y_test, svm_predictions, average="weighted", zero_division=0)
svm_f1 = f1_score(y_test, svm_predictions, average="weighted", zero_division=0)

print("SVM Model Results")
print("Accuracy:", round(svm_accuracy, 4))
print("Precision:", round(svm_precision, 4))
print("Recall:", round(svm_recall, 4))
print("F1 Score:", round(svm_f1, 4))

SVM Model Results
Accuracy: 0.9683
Precision: 0.9718
Recall: 0.9683
F1 Score: 0.9681

In [ ]:
from sklearn.naive_bayes import MultinomialNB

# Create Naive Bayes model
nb_model = MultinomialNB()

# Train the model
nb_model.fit(X_train, y_train)

# Predict on test data
nb_predictions = nb_model.predict(X_test)

# Evaluate
nb_accuracy = accuracy_score(y_test, nb_predictions)
nb_precision = precision_score(y_test, nb_predictions, average="weighted", zero_division=0)
nb_recall = recall_score(y_test, nb_predictions, average="weighted", zero_division=0)
nb_f1 = f1_score(y_test, nb_predictions, average="weighted", zero_division=0)

print("Naive Bayes Model Results")
print("Accuracy:", round(nb_accuracy, 4))
print("Precision:", round(nb_precision, 4))
print("Recall:", round(nb_recall, 4))
print("F1 Score:", round(nb_f1, 4))

Naive Bayes Model Results
Accuracy: 0.9841
Precision: 0.9873
Recall: 0.9841
F1 Score: 0.981

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Create Random Forest model
rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced"
)

# Train the model
rf_model.fit(X_train, y_train)

# Predict on test data
rf_predictions = rf_model.predict(X_test)

# Evaluate
rf_accuracy = accuracy_score(y_test, rf_predictions)
rf_precision = precision_score(y_test, rf_predictions, average="weighted", zero_division=0)
rf_recall = recall_score(y_test, rf_predictions, average="weighted", zero_division=0)
rf_f1 = f1_score(y_test, rf_predictions, average="weighted", zero_division=0)

print("Random Forest Model Results")
print("Accuracy:", round(rf_accuracy, 4))
print("Precision:", round(rf_precision, 4))
print("Recall:", round(rf_recall, 4))
print("F1 Score:", round(rf_f1, 4))

Random Forest Model Results
Accuracy: 0.9603
Precision: 0.9683
Recall: 0.9603
F1 Score: 0.9588

In [ ]:
model_results = pd.DataFrame({
    "Model": ["SVM", "Naive Bayes", "Random Forest"],
    "Accuracy": [svm_accuracy, nb_accuracy, rf_accuracy],
    "Precision": [svm_precision, nb_precision, rf_precision],
    "Recall": [svm_recall, nb_recall, rf_recall],
    "F1 Score": [svm_f1, nb_f1, rf_f1]
})

model_results = model_results.sort_values(by="F1 Score", ascending=False)

model_results

           Model  Accuracy  Precision    Recall  F1 Score
1    Naive Bayes  0.984127   0.987302  0.984127  0.981041
0            SVM  0.968254   0.971825  0.968254  0.968128
2  Random Forest  0.960317   0.968254  0.960317  0.958774

In [ ]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

models = {
    "SVM": svm_model,
    "Naive Bayes": nb_model,
    "Random Forest": rf_model
}

cv_results = []

for model_name, model in models.items():
    scores = cross_val_score(
        model,
        X,
        y_encoded,
        cv=cv,
        scoring="f1_weighted"
    )

    cv_results.append({
        "Model": model_name,
        "CV F1 Mean": scores.mean(),
        "CV F1 Std": scores.std()
    })

cv_results_df = pd.DataFrame(cv_results).sort_values(
    by="CV F1 Mean",
    ascending=False
)

cv_results_df

           Model  CV F1 Mean  CV F1 Std
2  Random Forest    0.981965   0.009531
1    Naive Bayes    0.981630   0.011056
0            SVM    0.966532   0.010595

In [ ]:
print("Naive Bayes Classification Report")
print(classification_report(
    y_test,
    nb_predictions,
    target_names=label_encoder.classes_,
    zero_division=0
))

Naive Bayes Classification Report
                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00         3
                                   AIDS       1.00      1.00      1.00         2
                                   Acne       1.00      1.00      1.00         2
                    Alcoholic hepatitis       1.00      1.00      1.00         3
                                Allergy       1.00      1.00      1.00         3
                              Arthritis       1.00      1.00      1.00         2
                       Bronchial Asthma       1.00      1.00      1.00         4
                   Cervical spondylosis       1.00      1.00      1.00         2
                            Chicken pox       1.00      1.00      1.00         4
                    Chronic cholestasis       1.00      0.33      0.50         3
                            Common Cold       1.00      1.00      1.00         3
                                 Dengue       1.00      1.00      1.00         4
                               Diabetes       1.00      1.00      1.00         4
           Dimorphic hemmorhoids(piles)       1.00      1.00      1.00         2
                          Drug Reaction       1.00      1.00      1.00         2
                       Fungal infection       1.00      1.00      1.00         3
                                   GERD       1.00      1.00      1.00         3
                        Gastroenteritis       1.00      1.00      1.00         2
                           Heart attack       1.00      1.00      1.00         2
                            Hepatitis B       1.00      1.00      1.00         3
                            Hepatitis C       1.00      1.00      1.00         3
                            Hepatitis D       0.80      1.00      0.89         4
                            Hepatitis E       1.00      1.00      1.00         3
                           Hypertension       1.00      1.00      1.00         3
                        Hyperthyroidism       1.00      1.00      1.00         4
                           Hypoglycemia       1.00      1.00      1.00         4
                         Hypothyroidism       1.00      1.00      1.00         4
                               Impetigo       1.00      1.00      1.00         3
                               Jaundice       1.00      1.00      1.00         3
                                Malaria       1.00      1.00      1.00         3
                               Migraine       1.00      1.00      1.00         3
                        Osteoarthristis       1.00      1.00      1.00         4
           Paralysis (brain hemorrhage)       1.00      1.00      1.00         2
                   Peptic ulcer disease       1.00      1.00      1.00         4
                              Pneumonia       1.00      1.00      1.00         4
                              Psoriasis       1.00      1.00      1.00         3
                           Tuberculosis       1.00      1.00      1.00         4
                                Typhoid       1.00      1.00      1.00         4
                Urinary tract infection       1.00      1.00      1.00         2
                         Varicose veins       1.00      1.00      1.00         2
                            hepatitis A       0.80      1.00      0.89         4

                               accuracy                           0.98       126
                              macro avg       0.99      0.98      0.98       126
                           weighted avg       0.99      0.98      0.98       126

In [ ]:
print("Random Forest Classification Report")
print(classification_report(
    y_test,
    rf_predictions,
    target_names=label_encoder.classes_,
    zero_division=0
))

Random Forest Classification Report
                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00         3
                                   AIDS       1.00      1.00      1.00         2
                                   Acne       1.00      1.00      1.00         2
                    Alcoholic hepatitis       1.00      1.00      1.00         3
                                Allergy       1.00      1.00      1.00         3
                              Arthritis       1.00      0.50      0.67         2
                       Bronchial Asthma       1.00      1.00      1.00         4
                   Cervical spondylosis       1.00      1.00      1.00         2
                            Chicken pox       1.00      1.00      1.00         4
                    Chronic cholestasis       0.67      0.67      0.67         3
                            Common Cold       1.00      1.00      1.00         3
                                 Dengue       1.00      1.00      1.00         4
                               Diabetes       1.00      1.00      1.00         4
           Dimorphic hemmorhoids(piles)       1.00      1.00      1.00         2
                          Drug Reaction       1.00      1.00      1.00         2
                       Fungal infection       1.00      1.00      1.00         3
                                   GERD       1.00      1.00      1.00         3
                        Gastroenteritis       1.00      1.00      1.00         2
                           Heart attack       1.00      1.00      1.00         2
                            Hepatitis B       1.00      1.00      1.00         3
                            Hepatitis C       0.60      1.00      0.75         3
                            Hepatitis D       0.75      0.75      0.75         4
                            Hepatitis E       1.00      1.00      1.00         3
                           Hypertension       1.00      1.00      1.00         3
                        Hyperthyroidism       1.00      1.00      1.00         4
                           Hypoglycemia       1.00      1.00      1.00         4
                         Hypothyroidism       1.00      1.00      1.00         4
                               Impetigo       1.00      1.00      1.00         3
                               Jaundice       1.00      1.00      1.00         3
                                Malaria       1.00      1.00      1.00         3
                               Migraine       1.00      1.00      1.00         3
                        Osteoarthristis       0.80      1.00      0.89         4
           Paralysis (brain hemorrhage)       1.00      1.00      1.00         2
                   Peptic ulcer disease       1.00      1.00      1.00         4
                              Pneumonia       1.00      1.00      1.00         4
                              Psoriasis       1.00      1.00      1.00         3
                           Tuberculosis       1.00      1.00      1.00         4
                                Typhoid       1.00      1.00      1.00         4
                Urinary tract infection       1.00      1.00      1.00         2
                         Varicose veins       1.00      1.00      1.00         2
                            hepatitis A       1.00      0.50      0.67         4

                               accuracy                           0.96       126
                              macro avg       0.97      0.96      0.96       126
                           weighted avg       0.97      0.96      0.96       126

In [ ]:
df["disease"] = df["disease"].replace({
    "Peptic ulcer diseae": "Peptic ulcer disease",
    "(vertigo) Paroymsal  Positional Vertigo": "Paroxysmal Positional Vertigo",
    "Dimorphic hemmorhoids(piles)": "Haemorrhoids / Piles",
    "Osteoarthristis": "Osteoarthritis",
    "hepatitis A": "Hepatitis A"
})

In [ ]:
# Clean disease names for professional app output
df["disease"] = df["disease"].str.strip()

df["disease"] = df["disease"].replace({
    "Peptic ulcer diseae": "Peptic ulcer disease",
    "(vertigo) Paroymsal  Positional Vertigo": "Paroxysmal Positional Vertigo",
    "Dimorphic hemmorhoids(piles)": "Haemorrhoids / Piles",
    "Osteoarthristis": "Osteoarthritis",
    "hepatitis A": "Hepatitis A"
})

print("Number of diseases:", df["disease"].nunique())
print(df["disease"].sort_values().unique())

Number of diseases: 41
['AIDS' 'Acne' 'Alcoholic hepatitis' 'Allergy' 'Arthritis'
 'Bronchial Asthma' 'Cervical spondylosis' 'Chicken pox'
 'Chronic cholestasis' 'Common Cold' 'Dengue' 'Diabetes' 'Drug Reaction'
 'Fungal infection' 'GERD' 'Gastroenteritis' 'Haemorrhoids / Piles'
 'Heart attack' 'Hepatitis A' 'Hepatitis B' 'Hepatitis C' 'Hepatitis D'
 'Hepatitis E' 'Hypertension' 'Hyperthyroidism' 'Hypoglycemia'
 'Hypothyroidism' 'Impetigo' 'Jaundice' 'Malaria' 'Migraine'
 'Osteoarthritis' 'Paralysis (brain hemorrhage)'
 'Paroxysmal Positional Vertigo' 'Peptic ulcer disease' 'Pneumonia'
 'Psoriasis' 'Tuberculosis' 'Typhoid' 'Urinary tract infection'
 'Varicose veins']

In [ ]:
X = df.drop(columns=["disease"])
y = df["disease"]

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)
print("Number of disease classes:", len(label_encoder.classes_))

X shape: (630, 130)
y shape: (630,)
Training data: (504, 130)
Testing data: (126, 130)
Number of disease classes: 41

In [ ]:
final_model = MultinomialNB()

final_model.fit(X_train, y_train)

final_predictions = final_model.predict(X_test)

final_accuracy = accuracy_score(y_test, final_predictions)
final_precision = precision_score(y_test, final_predictions, average="weighted", zero_division=0)
final_recall = recall_score(y_test, final_predictions, average="weighted", zero_division=0)
final_f1 = f1_score(y_test, final_predictions, average="weighted", zero_division=0)

print("Final Naive Bayes Model Results")
print("Accuracy:", round(final_accuracy, 4))
print("Precision:", round(final_precision, 4))
print("Recall:", round(final_recall, 4))
print("F1 Score:", round(final_f1, 4))

Final Naive Bayes Model Results
Accuracy: 0.9841
Precision: 0.9877
Recall: 0.9841
F1 Score: 0.9812

In [ ]:
import joblib

model_package = {
    "model": final_model,
    "model_name": "Naive Bayes",
    "label_encoder": label_encoder,
    "features": list(X.columns),
    "accuracy": final_accuracy,
    "precision": final_precision,
    "recall": final_recall,
    "f1_score": final_f1,
    "medical_disclaimer": "This app is an educational AI prototype and does not provide medical diagnosis or prescription advice."
}

joblib.dump(model_package, "disease_prediction_model.pkl")

print("Final model saved successfully!")
print("Saved file: disease_prediction_model.pkl")

Final model saved successfully!
Saved file: disease_prediction_model.pkl

In [ ]:
df.to_csv("clean_healthcare_training_dataset.csv", index=False)

print("Clean dataset saved successfully!")

Clean dataset saved successfully!

In [ ]:
from google.colab import files

files.download("disease_prediction_model.pkl")
files.download("clean_healthcare_training_dataset.csv")